# IDENTITY (ContextIdApplicationContextInitializer)
server:
  port: 8090
  address: localhost
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5


